(in-ns 'valuable-triangle.config)

(def subjects (list
  ["'What a meteorologist would say'" 2]
  ["Yellow things" 2]
  ["Hand gestures" 4]
  ["Parts of a tuxedo" 1]
  ["Comic strips" 1]
  ["Vicious things" 6]
  ["Things you avoid" 5]
  ["Places with a counter" 6]
  ["'What an uncle would say'" 2]
  ["Famous queens" 2]
  ["Why you stumble" 5]
  ["Damp things" 5]
  ["Things you crumple" 6]
  ["Why you play the lottery" 3]
  ["Board games" 1]
  ["'What Mick Jagger would say'" 3]
  ["Things that dissolve" 5]
  ["Foreign currencies" 1]
  ["'Why we went to the moon'" 5]
  ["Things with a crust" 3]
  ["Newspaper sections" 2]
  ["Things you flip" 4]
  ["Things that cause blisters" 4]
  ["Office supplies" 2]
  ["Horse racing terms" 3]
  ["African countries" 1]
  ["Things that are bleak" 6]
  ["'What ice would say'" 2]
))
